//! One-shot generator for the committed interop vectors. Run once to (re)write
//! `vectors/*.txt`; the committed files are the source of truth thereafter and
//! the tests/binary REPLAY them (they do not regenerate). Re-run only on a
//! deliberate protocol change (and bump PROTOCOL_VERSION).
//!
//!   cargo run --example gen_vectors

use pake::vectors::{derive, SeededRng};
use pake::{ServerSession};

struct Spec {
    name: &'static str,
    pin: &'static str,
    host_fp_hex: &'static str,
    seed_a: [u8; 32],
    seed_b: [u8; 32],
}

fn main() {
    let specs = [
        Spec {
            name: "basic-482173",
            pin: "482173",
            // SHA256 of the literal bytes "remotepair-test-host-key" (any fixed 32B).
            host_fp_hex: "8b1a9953c4611296a827abf8c47804d7e6c49c6b8f3e5c4f9d2a1b0e7c6d5a4b",
            seed_a: [0x11; 32],
            seed_b: [0x22; 32],
        },
        Spec {
            name: "pin-000000",
            pin: "000000",
            host_fp_hex: "3fdba35f04dc8c462986c992bcf875546257113072a909c162f7e470e581e278",
            seed_a: [0xA5; 32],
            seed_b: [0x5A; 32],
        },
    ];

    let dir = concat!(env!("CARGO_MANIFEST_DIR"), "/vectors");
    for s in &specs {
        let host_fp = {
            let raw = hex::decode(s.host_fp_hex).unwrap();
            let mut f = [0u8; 32];
            f.copy_from_slice(&raw);
            f
        };
        // Build a Vector with the inputs filled and outputs derived.
        let v = pake::vectors::Vector {
            name: s.name.to_string(),
            pin: s.pin.to_string(),
            host_fp,
            seed_a: s.seed_a,
            seed_b: s.seed_b,
            // placeholders; replaced by the derivation below
            msg_host: vec![],
            msg_client: vec![],
            host_mac: vec![],
            client_mac: vec![],
            shared_key: vec![],
            channel: vec![],
        };
        let d = derive(&v);
        // Sanity: re-run the host start to confirm determinism of msg_host.
        let (_srv, msg_host_again) =
            ServerSession::start_with_rng(s.pin, host_fp, SeededRng::from_seed(&s.seed_a));
        assert_eq!(d.msg_host, msg_host_again, "non-deterministic host msg");

        let body = format!(
            "# RemotePair PAKE interop vector — generated by examples/gen_vectors.rs\n\
             # Protocol: SPAKE2-Ed25519 / HKDF-SHA256 / HMAC-SHA256 (PROTOCOL.md v1).\n\
             # REPLAYED (not regenerated) by `cargo test -p pake` and\n\
             # `remote-pair-pake --selftest-vectors`. A mismatch fails CI.\n\
             name = {}\n\
             pin = {}\n\
             host_fp = {}\n\
             seed_a = {}\n\
             seed_b = {}\n\
             msg_host = {}\n\
             msg_client = {}\n\
             host_mac = {}\n\
             client_mac = {}\n\
             shared_key = {}\n\
             channel = {}\n",
            s.name,
            s.pin,
            hex::encode(host_fp),
            hex::encode(s.seed_a),
            hex::encode(s.seed_b),
            hex::encode(&d.msg_host),
            hex::encode(&d.msg_client),
            hex::encode(d.host_mac),
            hex::encode(d.client_mac),
            hex::encode(&d.shared_key),
            hex::encode(d.channel),
        );
        let path = format!("{dir}/{}.txt", s.name);
        std::fs::write(&path, body).unwrap();
        eprintln!("wrote {path}");
    }
}
