#!/bin/bash
# install.sh — RemotePair installer (role-based, reversible).
#
# Roles (--role):
#   host    Machine where claude runs with computer-use. RemotePairHost.app + LaunchAgent + approve (skill/rules) + watchdog.
#   client  Machine you sit at. Service "Launch Remote Pair" + launcher + remote-pair CLI. (No app/permissions/build needed.)
#   both    Both roles on one machine (default).
#
# All runtime state lives under ~/.remote-pair (self-contained). ~/.claude only receives the
# Claude harness (approve skill) — RemotePair behavior does not depend on ~/.claude being synced.
#
# Sync is OFF by default (opt-in). ~/.claude git backbone is set up only with --with-sync or SYNC_URL set.
# Every action is recorded in the manifest so uninstall.sh can precisely reverse it.
#
# Usage:
#   ./install.sh                      # role=both (interactive REMOTE_HOST prompt)
#   ./install.sh --role client        # Laptop: Service + launcher only (no build/permissions needed)
#   ./install.sh --role host          # Server: app + approve (requires a built build/RemotePairHost.app)
#   ./install.sh --with-sync          # + ~/.claude git backbone
#   REMOTE_HOST=my-mac ./install.sh --role client      # Non-interactive
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$HERE/config.sh"
. "$HERE/lib.sh"

ROLE=both; DO_NATIVE=1; DO_SYNC=0
[ -n "${SYNC_URL:-}" ] && DO_SYNC=1
while [ $# -gt 0 ]; do case "$1" in
  --role) ROLE="${2:-both}"; shift 2 ;;
  --role=*) ROLE="${1#*=}"; shift ;;
  --with-sync) DO_SYNC=1; shift ;;
  --no-sync) DO_SYNC=0; shift ;;
  --no-native) DO_NATIVE=0; shift ;;
  -h|--help) sed -n '2,26p' "$0"; exit 0 ;;
  *) echo "unknown arg: $1" >&2; exit 2 ;;
esac; done
case "$ROLE" in host|client|both) : ;; *) echo "invalid --role: $ROLE (host|client|both)" >&2; exit 2 ;; esac
MANIFEST="$RP_DIR/.manifest-$ROLE"

say()  { printf '\033[1;36m▸ %s\033[0m\n' "$*"; }
warn() { printf '\033[1;33m⚠ %s\033[0m\n' "$*" >&2; }
is_host()   { [ "$ROLE" = host ] || [ "$ROLE" = both ]; }
is_client() { [ "$ROLE" = client ] || [ "$ROLE" = both ]; }

_write_env() {
  local f="$1"; shift
  [ -e "$f" ] || record FILE "$f"
  { echo "# RemotePair config ($(basename "$f")) — written by install.sh. Safe to edit manually."
    local k; for k in "$@"; do printf '%s=%q\n' "$k" "${!k}"; done
  } > "$f"
}
write_config() {
  mk_dir "$RP_DIR"
  _write_env "$COMMON_ENV" "${COMMON_KEYS[@]}"
  if is_host;   then _write_env "$HOST_ENV"   "${HOST_KEYS[@]}"; fi
  if is_client; then _write_env "$CLIENT_ENV" "${CLIENT_KEYS[@]}"; fi
}

# ── 0. Input ──
say "RemotePair install — role=$ROLE, sync=$([ "$DO_SYNC" = 1 ] && echo on || echo off) (bundle=$BUNDLE_PREFIX, app=$APP_NAME)"
if is_client && [ -z "${REMOTE_HOST:-}" ] && [ -t 0 ]; then
  read -r -p "Remote host (mosh/ssh target; leave blank for local-only): " REMOTE_HOST || true
fi
[ -n "${REMOTE_HOST:-}" ] && say "Remote host = $REMOTE_HOST" || say "REMOTE_HOST not set (local-only mode)"

# ── Revert existing install before re-installing (idempotent) ──
if [ -f "$MANIFEST" ]; then say "Existing install detected — reverting before reinstall"; manifest_revert >/dev/null 2>&1 || true; fi
manifest_init
write_config
record NOTE "installed role=$ROLE at $(date '+%F %T') on $(hostname -s)"

# ── Common: umbrella CLI → PATH + log directory ──
say "remote-pair CLI → $LOCAL_BIN"
install_file "$GLUE_DIR/bin/remote-pair" "$LOCAL_BIN/remote-pair" 755
case ":$PATH:" in *":$LOCAL_BIN:"*) : ;; *) warn "$LOCAL_BIN is not in PATH — add it to your shell rc" ;; esac
mk_dir "$LOG_DIR"

# ── HOST: app + approve (skill/rules) + watchdog + LaunchAgent ──
if is_host; then
  say "[host] approve rules → $RULES_FILE"
  install_file "$GLUE_DIR/rules.txt" "$RULES_FILE"
  if [ -d "$REPO_ROOT/skills" ]; then
    say "[host] approve skill → $CLAUDE_DIR/skills (Claude harness location)"
    while IFS= read -r src; do
      rel="${src#"$REPO_ROOT/skills/"}"; install_file "$src" "$CLAUDE_DIR/skills/$rel"
    done < <(find "$REPO_ROOT/skills" -type f)
  fi
  # Remove legacy label names — idempotent, best-effort
  U=$(id -u)
  for L in com.ghyeong.remote-pair com.ghyeong.remote-pair-watchdog com.ghyeong.auto-approve com.ghyeong.auto-approve-watchdog com.x10lab.remote-pair com.x10lab.remote-pair-watchdog; do
    launchctl bootout "gui/$U/$L" 2>/dev/null || true
  done
  rm -rf "$HOME/Applications/RemotePair.app" "$HOME/Applications/AutoApprove.app" 2>/dev/null || true

  # watchdog
  install -d "$RP_DIR/bin" 2>/dev/null || mkdir -p "$RP_DIR/bin"
  write_file "$RP_DIR/bin/remote-pair-watchdog.sh" 755 <<W
#!/bin/bash
# remote-pair-watchdog.sh — Restart $APP_NAME when heartbeat goes stale. (generated by install.sh)
set -u
HB="$HEARTBEAT_FILE"; LOG="$LOG_FILE"
STALE=90; LABEL="gui/\$(id -u)/${APP_LABEL}"; now=\$(date +%s)
if [ -f "\$HB" ]; then
  age=\$(( now - \$(stat -f %m "\$HB" 2>/dev/null || echo 0) ))
  [ "\$age" -gt "\$STALE" ] && { launchctl kickstart -k "\$LABEL" >/dev/null 2>&1; printf '%s watchdog: stale %ss\n' "\$(date '+%F %T')" "\$age" >> "\$LOG"; }
else launchctl kickstart -k "\$LABEL" >/dev/null 2>&1; fi
W

  if [ "$DO_NATIVE" = 1 ]; then
    if [ -d "$REPO_ROOT/build/${APP_NAME}.app" ]; then
      say "[host] Installing app → $APP_PATH"
      [ -e "$APP_PATH" ] && rm -rf "$APP_PATH"
      mk_dir "$(dirname "$APP_PATH")"; record TREE "$APP_PATH"
      cp -R "$REPO_ROOT/build/${APP_NAME}.app" "$APP_PATH"
      xattr -dr com.apple.quarantine "$APP_PATH" 2>/dev/null || true
      if [ -x "$APP_PATH/Contents/Helpers/tmux-aqua" ]; then
        mk_dir "$LOCAL_BIN"; record FILE "$LOCAL_BIN/tmux-aqua"
        ln -sf "$APP_PATH/Contents/Helpers/tmux-aqua" "$LOCAL_BIN/tmux-aqua"
      fi
      app_plist="$LAUNCH_AGENTS/${APP_LABEL}.plist"; wd_plist="$LAUNCH_AGENTS/${WATCHDOG_LABEL}.plist"
      write_file "$app_plist" <<P
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>Label</key><string>${APP_LABEL}</string>
  <key>ProgramArguments</key><array><string>${APP_EXEC}</string></array>
  <key>RunAtLoad</key><true/><key>KeepAlive</key><true/>
  <key>ProcessType</key><string>Interactive</string>
  <key>StandardOutPath</key><string>${LOG_DIR}/remote-pair.out.log</string>
  <key>StandardErrorPath</key><string>${LOG_DIR}/remote-pair.err.log</string>
</dict></plist>
P
      write_file "$wd_plist" <<P
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>Label</key><string>${WATCHDOG_LABEL}</string>
  <key>ProgramArguments</key><array><string>/bin/bash</string><string>${RP_DIR}/bin/remote-pair-watchdog.sh</string></array>
  <key>RunAtLoad</key><true/><key>StartInterval</key><integer>30</integer>
  <key>StandardErrorPath</key><string>${LOG_DIR}/remote-pair-watchdog.err.log</string>
</dict></plist>
P
      U=$(id -u)
      launchctl bootstrap "gui/$U" "$app_plist" 2>/dev/null || launchctl kickstart -k "gui/$U/${APP_LABEL}" 2>/dev/null || true
      record LAUNCHCTL "$APP_LABEL" "$app_plist"
      launchctl bootstrap "gui/$U" "$wd_plist" 2>/dev/null || true
      record LAUNCHCTL "$WATCHDOG_LABEL" "$wd_plist"
      warn "One-time permission grant required: System Settings → Privacy & Security → Accessibility / Screen Recording → turn $APP_NAME ON"
    else
      warn "No build artifact: $REPO_ROOT/build/${APP_NAME}.app — run scripts/build-host.sh first (skipping app install)"
    fi
  fi
fi

# ── CLIENT: launcher + Service "Launch Remote Pair" ──
if is_client; then
  say "[client] launcher + Service"
  install -d "$RP_DIR/bin" 2>/dev/null || mkdir -p "$RP_DIR/bin"
  [ -f "$GLUE_DIR/bin/hangul-romanize" ] && install_file "$GLUE_DIR/bin/hangul-romanize" "$RP_DIR/bin/hangul-romanize" 755
  install_file "$GLUE_DIR/bin/remote-pair-launch" "$LAUNCHER" 755
  svc_src="$GLUE_DIR/services/Launch Remote Pair.workflow"
  svc_dst="$SERVICES_DIR/Launch Remote Pair.workflow"
  if [ -d "$svc_src" ]; then
    [ -e "$svc_dst" ] && rm -rf "$svc_dst"
    mk_dir "$SERVICES_DIR"; record TREE "$svc_dst"
    cp -R "$svc_src" "$svc_dst"
    [ "$SERVICES_DIR" = "$HOME/Library/Services" ] && /System/Library/CoreServices/pbs -flush 2>/dev/null || true
    say "  Service registered — Finder: right-click folder → Quick Actions → Launch Remote Pair"
  else
    warn "Service template not found: $svc_src (skipping Service install)"
  fi
fi

# ── SYNC (opt-in): ~/.claude git backbone (personal convenience — unrelated to RemotePair behavior) ──
if [ "$DO_SYNC" = 1 ]; then
  say "[sync] gitignore whitelist + git backbone"
  while IFS= read -r line; do
    [ -z "$line" ] && continue; case "$line" in \#*) continue ;; esac
    add_gitignore "$line"
  done < "$HERE/claude.gitignore"
  "$HERE/sync-setup.sh"
else
  say "sync off — ~/.claude not synced (enable with --with-sync)"
fi

say "Done. To uninstall:  $HERE/uninstall.sh"
record NOTE "install finished"

# ── client: SSH connectivity check (non-blocking advisory) ──
if is_client && [ -n "${REMOTE_HOST:-}" ]; then
  echo; say "[client] SSH connectivity check (remote-pair doctor)"
  "$LOCAL_BIN/remote-pair" doctor || warn "doctor reported issues — see above (install itself succeeded)"
fi

# ── client: interactive onboarding (tty only) ──
if is_client && [ -t 0 ]; then
  echo
  "$LOCAL_BIN/remote-pair" onboard || true
fi
